trr_race_manager_node:
  nb_lap: 1

trr_vision_traffic_light_node:
  roi_xc: 450
  roi_yc: 150
  roi_dx: 200
  roi_dy: 100
  # green mask
  g_hc:    55
  g_hs:    12
  g_smin: 140
  g_smax: 255
  g_vmin:  70
  g_vmax: 255
  # red mask
  r_hc:   7
  r_hs:    10
  r_smin: 175
  r_smax: 255
  r_vmin:  70
  r_vmax: 255

trr_vision_start_finish_node:
  # global
  roi_yt: 80
  min_area: 3000
  min_eccentricity: 0.8
  # green mask
  g_hc:    53
  g_hs:    10
  g_smin: 150
  g_smax: 255
  g_vmin:  90
  g_vmax: 255
  # red mask
  r_hc:   190
  r_hs:    10
  r_smin: 105
  r_smax: 255
  r_vmin:  70
  r_vmax: 255

trr_vision_lane_node:
  mask_min_area: 100
  bridge_offset: 15
  
trr_guidance_node:
  vel_sp: 2.
  lookahead_dist: 1.2
  path_name: guesdes/track_trr_0.npz 

trr_state_estimator_node:
  path_filename: /home/poine/work/two_d_guidance/paths/guesdes/track_trr_0.npz

trr_state_estimator_display_node:
  path_filename: /home/poine/work/two_d_guidance/paths/guesdes/track_trr_0.npz
