
odrive_can_cpp_ext.so: odrive_can_cpp_ext.pyx setup_odrive_can_cpp_ext.py
	python setup_odrive_can_cpp_ext.py build_ext --inplace

clean:
	rm -f *~ *.pyc odrive_can_cpp_ext.cpp odrive_can_cpp_ext.so
