
joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  extra_joints:
    - name: '_caster_ax1_to_ax2_joint'
    - name: '_caster_fork_to_wheel_joint'

diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 100
  
  enable_odom_tf: true
  base_frame_id: base_link
  odom_frame_id: odom
    
  pose_covariance_diagonal : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
  twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  # Wheel separation and radius multipliers
  wheel_radius: 0.0825
  wheel_separation: 0.275
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      #max_velocity           : 0.9  # m/s
      #min_velocity           : -0.9 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.5  # m/s^2
      min_acceleration       : -1.5 # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      #max_velocity           : 0.5  # rad/s
      has_acceleration_limits: false
      #max_acceleration       : 1.5  # rad/s^2
