# regular joystick
teleop_twist_joy:
   axis_linear:  1
   scale_linear: 0.75
   scale_linear_turbo: 2.5
   axis_angular: 2
   scale_angular: 2.5
   enable_button: 4
   enable_turbo_button: 5

joy_node:
  deadzone: 0.01
  autorepeat_rate: 20
